"""remove token version from user

Revision ID: 109ba6c89516
Revises: 066c1b8de564
Create Date: 2026-01-10 17:03:54.510573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '109ba6c89516'
down_revision: Union[str, Sequence[str], None] = '066c1b8de564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_version', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
