"""pending message model

Revision ID: 2d7919839dc3
Revises: a3c968d30e29
Create Date: 2026-01-23 20:59:09.933739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7919839dc3'
down_revision: Union[str, Sequence[str], None] = 'a3c968d30e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('pending_conversation_id', sa.String(), nullable=False),
    sa.Column('sender_visitor_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pending_conversation_id'], ['pending_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_visitor_id'], ['visitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_messages_pending_conversation_id'), 'pending_messages', ['pending_conversation_id'], unique=False)
    op.create_index(op.f('ix_pending_messages_sender_visitor_id'), 'pending_messages', ['sender_visitor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_messages_sender_visitor_id'), table_name='pending_messages')
    op.drop_index(op.f('ix_pending_messages_pending_conversation_id'), table_name='pending_messages')
    op.drop_table('pending_messages')
    # ### end Alembic commands ###
