"""add display id for visitor

Revision ID: 6fefb26d6e0a
Revises: bcf8c6e624cc
Create Date: 2026-01-29 00:25:03.984153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fefb26d6e0a'
down_revision: Union[str, Sequence[str], None] = 'bcf8c6e624cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('display_id', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_visitors_display_id'), 'visitors', ['display_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitors_display_id'), table_name='visitors')
    op.drop_column('visitors', 'display_id')
    # ### end Alembic commands ###
