"""link widget, conversation and pending conversation

Revision ID: 7d69930b3204
Revises: 6fefb26d6e0a
Create Date: 2026-02-03 20:58:32.061674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d69930b3204'
down_revision: Union[str, Sequence[str], None] = '6fefb26d6e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('widget_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_conversations_widget_id'), 'conversations', ['widget_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'widgets', ['widget_id'], ['id'], ondelete='CASCADE')
    op.add_column('pending_conversations', sa.Column('widget_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_pending_conversations_widget_id'), 'pending_conversations', ['widget_id'], unique=False)
    op.create_foreign_key(None, 'pending_conversations', 'widgets', ['widget_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pending_conversations', type_='foreignkey')
    op.drop_index(op.f('ix_pending_conversations_widget_id'), table_name='pending_conversations')
    op.drop_column('pending_conversations', 'widget_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_widget_id'), table_name='conversations')
    op.drop_column('conversations', 'widget_id')
    # ### end Alembic commands ###
