"""actor model

Revision ID: 978320c5b569
Revises: 86cf7944d70a
Create Date: 2026-01-16 22:33:10.079083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '978320c5b569'
down_revision: Union[str, Sequence[str], None] = '86cf7944d70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('user', 'visitor', name='actor_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actors_type'), 'actors', ['type'], unique=False)
    op.add_column('messages', sa.Column('sender_actor_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_messages_sender_actor_id'), 'messages', ['sender_actor_id'], unique=False)
    op.drop_constraint(op.f('messages_sender_user_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_visitor_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'actors', ['sender_actor_id'], ['id'])
    op.drop_column('messages', 'sender_visitor_id')
    op.drop_column('messages', 'sender_user_id')
    op.add_column('users', sa.Column('actor_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['actor_id'])
    op.create_foreign_key(None, 'users', 'actors', ['actor_id'], ['id'])
    op.add_column('visitors', sa.Column('actor_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'visitors', ['actor_id'])
    op.create_foreign_key(None, 'visitors', 'actors', ['actor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visitors', type_='foreignkey')
    op.drop_constraint(None, 'visitors', type_='unique')
    op.drop_column('visitors', 'actor_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'actor_id')
    op.add_column('messages', sa.Column('sender_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('sender_visitor_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_visitor_id_fkey'), 'messages', 'visitors', ['sender_visitor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('messages_sender_user_id_fkey'), 'messages', 'users', ['sender_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_messages_sender_actor_id'), table_name='messages')
    op.drop_column('messages', 'sender_actor_id')
    op.drop_index(op.f('ix_actors_type'), table_name='actors')
    op.drop_table('actors')
    # ### end Alembic commands ###
