"""clean models

Revision ID: a3c968d30e29
Revises: 978320c5b569
Create Date: 2026-01-17 20:05:29.953302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c968d30e29'
down_revision: Union[str, Sequence[str], None] = '978320c5b569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('pending_conversations', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('refresh_tokens', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pending_conversations', 'accepted_at')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('conversations', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
