"""allow close pending conversation

Revision ID: bcf8c6e624cc
Revises: 2d7919839dc3
Create Date: 2026-01-23 22:02:22.041284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcf8c6e624cc'
down_revision: Union[str, Sequence[str], None] = '2d7919839dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_conversations', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_conversations', 'closed_at')
    # ### end Alembic commands ###
