"""no slug for widget

Revision ID: c479aa7b3982
Revises: bff1b1de8110
Create Date: 2026-01-14 00:19:45.541544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c479aa7b3982'
down_revision: Union[str, Sequence[str], None] = 'bff1b1de8110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_widget_slug'), 'widgets', type_='unique')
    op.drop_column('widgets', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widgets', sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_widget_slug'), 'widgets', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
